---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: pr-template
spec:
  params:
    - name: ibmcloud-api
      description: the ibmcloud api
      default: https://cloud.ibm.com
    - name: target-repository
      description: the repo integration name
    - name: target-branch
      description: target branch
    - name: pr-repository
      description: PR url
    - name: pr-branch
      description: branch
    - name: pr-commit-id
      description: commit id
    - name: pipeline-debug
      description: toggles debug mode for the pipeline
  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: pr-pipeline
        workspaces:
          - name: pipeline-ws
            persistentVolumeClaim:
              claimName: pipelinerun-$(uid)-pvc
        params:
          - name: ibmcloud-api
            value: $(params.ibmcloud-api)
          - name: pr-repository
            value: $(params.pr-repository)
          - name: pr-branch
            value: $(params.pr-branch)
          - name: pr-commit-id
            value: $(params.pr-commit-id)
          - name: target-repository
            value: $(params.target-repository)
          - name: target-branch
            value: $(params.target-branch)
          - name: pipeline-debug
            value: $(params.pipeline-debug)
