version: '2'
messages:
  $i18n: locales.yml
template:
  name:
    $ref: "#/messages/template.name"
  description:
    $ref: "#/messages/template.description"
  header: '![](toolchain.svg?localize)'
  icon: secure-lock-helm.svg
  required:
    - build
    - repo
  info:
    # compute the git url and branch values dynamically so that they remain correct when repo is forked etc. 
    # note: `repository` url param must always be provided while the `branch` url param is optional
    # the computed urls are of the same format as the original static urls shown above
    git url: >
        '[' + $env.repository + '](' + $env.repository + ')'
    git branch: >
        $env.branch ?
          '[' + $env.branch + ']('+ $env.repository + '/tree/' + $env.branch + ')' :
          '[master]('+ $env.repository + '/tree/master)'
toolchain:
  name: 'helm-toolchain-{{timestamp}}'
  template:
    getting_started:
     $ref: "#/messages/template.gettingStarted"
services:
  repo:
    $switch:
      - $expr: $env.source_provider
      - $default: 'hostedgit'
        service_id: hostedgit
        parameters:
          repo_name: 'hello-helm-{{timestamp}}'
          repo_url: >
            $env.type === 'link' ? 
              $env.app_repo : 'https://github.com/open-toolchain/hello-helm'
          source_repo_url: >
            $env.type === 'fork' || $env.type === 'clone' ? 
              $env.app_repo : ''
          type: $env.type || 'clone'
          has_issues: true
          enable_traceability: true
      - $case: 'githubconsolidated'
        service_id: githubconsolidated
        parameters:
          repo_name: 'hello-helm-{{timestamp}}'
          repo_url: >
            $env.type === 'link' ? 
              $env.app_repo : 'https://github.com/open-toolchain/hello-helm'
          source_repo_url: >
            $env.type === 'fork' || $env.type === 'clone' ?
              $env.app_repo : ''
          type: $env.type  || 'clone'
          visibility: public
      - $case: 'github_integrated'
        service_id: github_integrated
        parameters:
          repo_name: 'hello-helm-{{timestamp}}'
          repo_url: >
            $env.type === 'link' ? 
              $env.app_repo : 'https://github.com/open-toolchain/hello-helm'
          source_repo_url: >
            $env.type === 'fork' || $env.type === 'clone' ? 
              $env.app_repo : ''
          type: >
            $env.type !== undefined ? 
              $env.type : 'clone'
          has_issues: true
          enable_traceability: true
      - $case: 'bitbucketgit'
        service_id: bitbucketgit
        parameters:
          repo_name: 'hello-helm-{{timestamp}}'
          repo_url: >
            $env.type === 'link' ? 
              $env.app_repo : 'https://github.com/open-toolchain/hello-helm'
          source_repo_url: >
            $env.type === 'fork' || $env.type === 'clone' ? 
              $env.app_repo : ''
          type: >
            $env.type !== undefined ? 
              $env.type : 'clone'
          has_issues: true
          enable_traceability: true
  build:
    service_id: pipeline
    parameters:
      services:
        - repo
      name: 'hello-helm-{{timestamp}}'
      ui-pipeline: true
      configuration:
        content:
          $text: pipeline.yml
        env:
          GIT_REPO: repo
          CF_APP_NAME: '{{form.pipeline.parameters.app-name}}'
          REGISTRY_REGION_ID: '{{form.pipeline.parameters.registry-region}}'
          REGISTRY_NAMESPACE: '{{form.pipeline.parameters.registry-namespace}}'
          API_KEY: '{{form.pipeline.parameters.api-key}}'
          PROD_REGION_ID: '{{form.pipeline.parameters.prod-region}}'
          PROD_RESOURCE_GROUP: '{{form.pipeline.parameters.prod-resource-group}}'
          PROD_CLUSTER_NAME: '{{form.pipeline.parameters.prod-cluster-name}}'
          PROD_CLUSTER_NAMESPACE: '{{form.pipeline.parameters.prod-cluster-namespace}}'
        execute: true
  webide:
    service_id: orion
form:
  pipeline:
    parameters:
      app-name: '{{services.repo.parameters.repo_name}}'
      prod-cluster-namespace: prod
    schema:
      $ref: deploy.json
